language: php

php:
  - 5.5
  - 5.4
  - 5.3
  - hhvm

install:
   - composer install

script:
   - mkdir -p build/logs
   - ./vendor/bin/phpunit --coverage-clover ./build/logs/clover.xml tests/

after_script:
   - ./vendor/bin/coveralls -v
