language: php

php:
  - 5.5
  - 5.4
  - 5.3
  - hhvm

install:
   - composer install
   - composer update

script:
   - mkdir -p build/logs
   - ./vendor/bin/phpunit --coverage-clover ./build/logs/clover.xml tests/

after_script:
   - ./vendor/bin/coveralls -v
   - wget --output-document=build/ocular.phar https://scrutinizer-ci.com/ocular.phar
   - php build/ocular.phar code-coverage:upload --format=php-clover ./build/logs/clover.xml
